INSERT INTO role (id, name) SELECT 0, 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_ADMIN');
INSERT INTO role (id, name) SELECT 1, 'ROLE_STUDENT' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_STUDENT');
INSERT INTO role (id, name) SELECT 2, 'ROLE_TEACHER' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_TEACHER');
